fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_profile_edit:
    path: /profile/edit
    defaults:
        _controller: FOSUserBundle:Profile:edit

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

edukodas_user:
    resource: "@EdukodasUserBundle/Resources/config/routing.yml"
    prefix: /

edukodas_tasks:
    resource: "@EdukodasTasksBundle/Resources/config/routing.yml"
    prefix: /tasks

edukodas_points:
    resource: "@EdukodasStatisticsBundle/Resources/config/routing.yml"
    prefix: /points

edukodas_profile:
    resource: "@EdukodasProfileBundle/Resources/config/routing.yml"
    prefix: /profile

edukodas_search:
    resource: "@EdukodasSearchBundle/Resources/config/routing.yml"
    prefix: /search

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /login
        permanent: true
