edukodas_point_history_list:
    path:     /list
    defaults: { _controller: EdukodasStatisticsBundle:PointHistory:list }

edukodas_points_add:
    path:     /add
    defaults: { _controller: EdukodasStatisticsBundle:PointHistory:add}
